// Code generated by "stringer -type=ObjectError"; DO NOT EDIT

package gojsonrpc

import "fmt"

const _ObjectError_name = "InvalidNotificationInvalidParamsTypeInvalidRequestInvalidParamsTypeInvalidResponseNilError"

var _ObjectError_index = [...]uint8{0, 36, 67, 90}

func (i ObjectError) String() string {
	if i < 0 || i >= ObjectError(len(_ObjectError_index)-1) {
		return fmt.Sprintf("ObjectError(%d)", i)
	}
	return _ObjectError_name[_ObjectError_index[i]:_ObjectError_index[i+1]]
}
